#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := $(APP_PROJECT_NAME)
BUILD_DIR_BASE = $(APP_BUILD_DIR)

include $(IDF_PATH)/make/project.mk

